version: '3.7'
services:
  timburr:
    container_name: timburr
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
      network: host
    volumes:
    - "./conf:/app/conf"
    extra_hosts:
    - "host.docker.internal:host-gateway"
